name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Quellcode auschecken
        uses: actions/checkout@v4

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Abhängigkeiten installieren
        run: npm ci

      - name: TypeScript kompilieren
        run: tsc

      - name: NestJS bauen
        run: npm run build

      - name: Tests ausführen
        run: echo "Erfolgreich geprompted"